// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhishingDetector.API.Data;

#nullable disable

namespace PhishingDetector.API.Migrations
{
    [DbContext(typeof(PhishingDbContext))]
    partial class PhishingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhishingDetector.Core.Models.EmailAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentAnalysis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContentRiskScore")
                        .HasColumnType("integer");

                    b.Property<string>("HeaderAnalysis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HeaderRiskScore")
                        .HasColumnType("integer");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Indicators")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OverallRisk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OverallRiskScore")
                        .HasColumnType("integer");

                    b.Property<long>("ProcessingTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlAnalysis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UrlRiskScore")
                        .HasColumnType("integer");

                    b.Property<string>("Urls")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedAt");

                    b.HasIndex("OverallRisk");

                    b.ToTable("EmailAnalyses");
                });
#pragma warning restore 612, 618
        }
    }
}
